name: CI-CD

on: push

jobs:
  CI-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remote credentials
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_S3_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_S3_SEC_ACCESS }}

      - name: DVC Pull
        run: |
          dvc pull

      - name: Run Appllication
        run: |
          nohup streamlit run app.py --server.port 8000 &
          sleep 30 

      - name: Test App
        run: |
          pytest test_app.py
      
      - name: Stop Streamlit app
        run: |
          pkill -f "streamlit run"

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spotify_recommender_system:latest .

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spotify_recommender_system:latest
      
      - name: Trigger Deploy on Render
        if: success()
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering Render deployment..."
          echo "Service ID: $RENDER_SERVICE_ID"

          RESPONSE=$(curl -s -w "\nHTTP_STATUS=%{http_code}\n" \
            -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY")

          echo "------ Render Response ------"
          echo "$RESPONSE"
          echo "-----------------------------"