name: CI-CD

on: push

jobs:
  CI-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remote credentials
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_S3_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_S3_SEC_ACCESS }}

      - name: DVC Pull
        run: |
          dvc pull

      - name: Run Appllication
        run: |
          nohup streamlit run app.py --server.port 8000 &
          sleep 30 

      - name: Test App
        run: |
          pytest test_app.py
      
      - name: Stop Streamlit app
        run: |
          pkill -f "streamlit run"